[project]
name = "tbgi"
version = "0.1.0"
description = "Vergelijk TBG-I (Terugmelding BekostigingsGrondslagen Individueel) met gegevens in Somtoday LVS."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>1.21.1",
    "openpyxl>=3.1.5",
    "pandas>1.3.1",
]
