class TbgiBestand:
    TBG_I_AANMAAK_DATUMTIJD = "TBG_I_AANMAAK_DATUMTIJD"
    TBG_I_AANMAAK_DATUMTIJD_COL_NAME = f'#{TBG_I_AANMAAK_DATUMTIJD}'
    BRIN = "BRIN"
    REGEL_NUMMER = "REGEL_NUMMER"
    BSN = "BSN"
    OWN = "OWN"
    TELDATUM = "TELDATUM"
    SOORT_TELDATUM = "SOORT_TELDATUM"
    BEKOSTIGINGSJAAR = "BEKOSTIGINGSJAAR"
    INSCHRIJVINGVOLGNUMMER = "INSCHRIJVINGVOLGNUMMER"
    VESTIGING = "VESTIGING"
    OPLEIDINGCODE = "OPLEIDINGCODE"
    LEERJAAR = "LEERJAAR"
    INDICATIE_BEKOSTIGBAAR = "INDICATIE_BEKOSTIGBAAR"
    BEKOSTIGINGSSTATUS = "BEKOSTIGINGSSTATUS"
    STATUS_BEPALING = "STATUS_BEPALING"
    DATUM_AANVRAAG_OBO = "DATUM_AANVRAAG_OBO"
    TERUGMELDINGSREDEN = "TERUGMELDINGSREDEN"
    DATUM_TIJD_BEPALING_GRONDSLAGEN = "DATUM_TIJD_BEPALING_GRONDSLAGEN"
    ORGANISATIE_IDENTIFICATIE_NUMMER = "ORGANISATIE_IDENTIFICATIE_NUMMER"
    TARIEFGROEP_EXPLOITATIE = "TARIEFGROEP_EXPLOITATIE"
    INDICATIE_DISPENSATIE_PRO = "INDICATIE_DISPENSATIE_PRO"
    IND_UITBESTEDING_MET_GED_BEKOSTIGING = "IND_UITBESTEDING_MET_GED_BEKOSTIGING"
    INDICATIE_HERPROFILEERDER = "INDICATIE_HERPROFILEERDER"
    INDICATIE_APC_GEBIED = "INDICATIE_APC_GEBIED"
    DREMPELGROEP_LPA = "DREMPELGROEP_LPA"
    DATUM_BINNENKOMST_IN_NL = "DATUM_BINNENKOMST_IN_NL"
    CATEGORIE_NK = "CATEGORIE_NK"
    SIGNAAL_1 = "SIGNAAL_1"
    PARAMETER_11 = "PARAMETER_11"
    PARAMETER_12 = "PARAMETER_12"
    PARAMETER_13 = "PARAMETER_13"
    PARAMETER_14 = "PARAMETER_14"
    PARAMETER_15 = "PARAMETER_15"
    SL_OMSCHRIJVING_1 = "SL_OMSCHRIJVING_1"
    SIGNAAL_2 = "SIGNAAL_2"
    PARAMETER_21 = "PARAMETER_21"
    PARAMETER_22 = "PARAMETER_22"
    PARAMETER_23 = "PARAMETER_23"
    PARAMETER_24 = "PARAMETER_24"
    PARAMETER_25 = "PARAMETER_25"
    SL_OMSCHRIJVING_2 = "SL_OMSCHRIJVING_2"
    SIGNAAL_3 = "SIGNAAL_3"
    PARAMETER_31 = "PARAMETER_31"
    PARAMETER_32 = "PARAMETER_32"
    PARAMETER_33 = "PARAMETER_33"
    PARAMETER_34 = "PARAMETER_34"
    PARAMETER_35 = "PARAMETER_35"
    SL_OMSCHRIJVING_3 = "SL_OMSCHRIJVING_3"
    SIGNAAL_4 = "SIGNAAL_4"
    PARAMETER_41 = "PARAMETER_41"
    PARAMETER_42 = "PARAMETER_42"
    PARAMETER_43 = "PARAMETER_43"
    PARAMETER_44 = "PARAMETER_44"
    PARAMETER_45 = "PARAMETER_45"
    SL_OMSCHRIJVING_4 = "SL_OMSCHRIJVING_4"
    SIGNAAL_5 = "SIGNAAL_5"
    PARAMETER_51 = "PARAMETER_51"
    PARAMETER_52 = "PARAMETER_52"
    PARAMETER_53 = "PARAMETER_53"
    PARAMETER_54 = "PARAMETER_54"
    PARAMETER_55 = "PARAMETER_55"
    SL_OMSCHRIJVING_5 = "SL_OMSCHRIJVING_5"
    FASE = "FASE"
    INDICATIE_NK_KORTER_DAN_JAAR = "INDICATIE_NK_KORTER_DAN_JAAR"
    TARIEF = "TARIEF"

    CSV_HEADER = [
        TBG_I_AANMAAK_DATUMTIJD_COL_NAME, BRIN, REGEL_NUMMER, BSN, OWN, TELDATUM, SOORT_TELDATUM, BEKOSTIGINGSJAAR,
        INSCHRIJVINGVOLGNUMMER, VESTIGING, OPLEIDINGCODE, LEERJAAR, INDICATIE_BEKOSTIGBAAR, BEKOSTIGINGSSTATUS,
        STATUS_BEPALING, DATUM_AANVRAAG_OBO, TERUGMELDINGSREDEN, DATUM_TIJD_BEPALING_GRONDSLAGEN,
        ORGANISATIE_IDENTIFICATIE_NUMMER, TARIEFGROEP_EXPLOITATIE, INDICATIE_DISPENSATIE_PRO,
        IND_UITBESTEDING_MET_GED_BEKOSTIGING, INDICATIE_HERPROFILEERDER, INDICATIE_APC_GEBIED, DREMPELGROEP_LPA,
        DATUM_BINNENKOMST_IN_NL, CATEGORIE_NK,
        SIGNAAL_1, PARAMETER_11, PARAMETER_12, PARAMETER_13, PARAMETER_14, PARAMETER_15, SL_OMSCHRIJVING_1,
        SIGNAAL_2, PARAMETER_21, PARAMETER_22, PARAMETER_23, PARAMETER_24, PARAMETER_25, SL_OMSCHRIJVING_2,
        SIGNAAL_3, PARAMETER_31, PARAMETER_32, PARAMETER_33, PARAMETER_34, PARAMETER_35, SL_OMSCHRIJVING_3,
        SIGNAAL_4, PARAMETER_41, PARAMETER_42, PARAMETER_43, PARAMETER_44, PARAMETER_45, SL_OMSCHRIJVING_4,
        SIGNAAL_5, PARAMETER_51, PARAMETER_52, PARAMETER_53, PARAMETER_54, PARAMETER_55, SL_OMSCHRIJVING_5,
        FASE, INDICATIE_NK_KORTER_DAN_JAAR, TARIEF
    ]

    DATETIME_COLUMNS = [TBG_I_AANMAAK_DATUMTIJD_COL_NAME, DATUM_TIJD_BEPALING_GRONDSLAGEN]
    DATE_COLUMNS = [TELDATUM, DATUM_AANVRAAG_OBO, DATUM_BINNENKOMST_IN_NL]
    INT_COLUMNS = [REGEL_NUMMER, BEKOSTIGINGSJAAR, LEERJAAR, SIGNAAL_1, SIGNAAL_2, SIGNAAL_3, SIGNAAL_4, SIGNAAL_5]
    BOOL_COLUMNS = [
        INDICATIE_BEKOSTIGBAAR,
        IND_UITBESTEDING_MET_GED_BEKOSTIGING,
        INDICATIE_HERPROFILEERDER,
        INDICATIE_APC_GEBIED,
        INDICATIE_NK_KORTER_DAN_JAAR,
        INDICATIE_DISPENSATIE_PRO
    ]

    TRUE_VALUES = ['J', 'j']
    FALSE_VALUES = ['N', 'n']

    COLUMN_TYPES = {BRIN: 'category',
                    REGEL_NUMMER: 'Int64',
                    BSN: 'Int64',
                    OWN: 'Int64',
                    SOORT_TELDATUM: 'category',
                    BEKOSTIGINGSJAAR: 'Int16',
                    VESTIGING: 'category',
                    INSCHRIJVINGVOLGNUMMER: 'string',
                    OPLEIDINGCODE: 'category',
                    LEERJAAR: 'Int64',
                    INDICATIE_BEKOSTIGBAAR: 'category',
                    BEKOSTIGINGSSTATUS: 'category',
                    STATUS_BEPALING: 'category',
                    TERUGMELDINGSREDEN: 'category',
                    ORGANISATIE_IDENTIFICATIE_NUMMER: 'category',
                    TARIEFGROEP_EXPLOITATIE: 'category',
                    INDICATIE_DISPENSATIE_PRO: 'category',
                    IND_UITBESTEDING_MET_GED_BEKOSTIGING: 'category',
                    INDICATIE_HERPROFILEERDER: 'category',
                    INDICATIE_APC_GEBIED: 'category',
                    DREMPELGROEP_LPA: 'category',
                    CATEGORIE_NK: 'category',
                    SIGNAAL_1: 'category',
                    SL_OMSCHRIJVING_1: 'category',
                    PARAMETER_11: 'string',
                    PARAMETER_12: 'string',
                    PARAMETER_13: 'string',
                    PARAMETER_14: 'string',
                    PARAMETER_15: 'string',
                    SIGNAAL_2: 'category',
                    SL_OMSCHRIJVING_2: 'category',
                    PARAMETER_21: 'string',
                    PARAMETER_22: 'string',
                    PARAMETER_23: 'string',
                    PARAMETER_24: 'string',
                    PARAMETER_25: 'string',
                    SIGNAAL_3: 'category',
                    SL_OMSCHRIJVING_3: 'category',
                    PARAMETER_31: 'string',
                    PARAMETER_32: 'string',
                    PARAMETER_33: 'string',
                    PARAMETER_34: 'string',
                    PARAMETER_35: 'string',
                    SIGNAAL_4: 'category',
                    SL_OMSCHRIJVING_4: 'category',
                    PARAMETER_41: 'string',
                    PARAMETER_42: 'string',
                    PARAMETER_43: 'string',
                    PARAMETER_44: 'string',
                    PARAMETER_45: 'string',
                    SIGNAAL_5: 'category',
                    SL_OMSCHRIJVING_5: 'category',
                    PARAMETER_51: 'string',
                    PARAMETER_52: 'string',
                    PARAMETER_53: 'string',
                    PARAMETER_54: 'string',
                    PARAMETER_55: 'string',
                    FASE: 'category',
                    INDICATIE_NK_KORTER_DAN_JAAR: 'category',
                    TARIEF: 'category'
                    }
